### PR TITLE
Created an automated build script #5

### PR DESCRIPTION
**Pull request by DamianReeves**
This is a good start but there are a couple of tests which file sometimes when I run them outside of the script. They seem to fail all the time with the script.

### What Works###
- [x] Successfully perform build
- [x] Run unit tests
- [x] Create NuGet Packages

### Known Issues###
- [ ] All Unit Tests should pass
    - *Some Are failing but they have been skipped by applying traits, and skipping the known failing tests. This however should be corrected at some point.*
- [ ] Build documentation 
    -  *was considered out of scope for me*

### CODE REVIEW

**Comment by DamianReeves** [comment]
I can't seem to get some of the tests to pass when run either directly from the build script or run in AppVeyor.

I added xUnit trait to some tests:
- `[Trait("Category","Timeout")` was added to the Timeout tests which seem to fail occasionally even when directly invoked from the Visual Studio test runner
- `[Trait("Investigate","True")` was added to some other tests which fail only in AppVeyor

**Comment by nvivo** [comment]
@DamianReeves 

This is great! Let me just take a look at the tests and appveyour to see what happens with those tests.

Do you have more commits planned for this PR?

**Comment by DamianReeves** [comment]
No more commits planned. I'm embarrassed I ended up with so many before I realized that the tests failing was a known issue reported the day before.

Also concerning the usage of Paket here are my thoughts:
 - If we use this pull request with Paket it allows us to jump start CI quickly
 - When there is more clarity on the dotnet command line tools I think it makes sense to switch to that later on
- So if we plan on switching to the dotnet commandline, then we can modify the build and CI stuff at that time since that would be impacted by such a switch

Thoughts?

**Comment by nvivo** [comment]
I agree. Let's get CI going and fix the tests later.

About the commits, it's a good practice to squash before submiting a PR. In TortoiseGit it's simple to rebase + squash all comits into one. Then you just force push your branch to github, it should reflect here.

**Comment by DamianReeves** [comment]
Closing this one as I have a squashed pull request as requested.

**Pull request closed without merging**
