### PR TITLE
Support for SQLite

### LINKED ISSUE #38: Add Support for SQLite

### PR DESCRIPTION
**Pull request by pvivera**
Resolve #38

### CODE REVIEW

**Comment by DamianReeves** [comment]
Awesome. Thanks! 
I'll review and merge.

**Comment by pvivera** [comment]
I'll do a new commit in a few minutes to clean up some stuff.

**Comment by DamianReeves** [comment]
Cool let me know when its all good to merge

**Comment by pvivera** [comment]
Done. The only remaining thing is create a nuget package for it, but I think it better create another issue.

**Pull request merged**
